#!/usr/bin/env sh
set -eu

# Generate production .env from template with random secrets.
# Existing .env is left unchanged unless FORCE_ENV=1.
#
# Optional environment variables:
#   ADMIN_API_DEFAULT_ADMIN_PASSWORD
#   AGENT_LLM_BASE_URL
#   AGENT_LLM_API_KEY
#   AGENT_LLM_MODEL

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"
TEMPLATE="$ROOT_DIR/deploy/env.production.example"

if [ -f "$ENV_FILE" ] && [ "${FORCE_ENV:-0}" != "1" ]; then
    echo "Using existing .env"
    exit 0
fi

if ! command -v python3 >/dev/null 2>&1; then
    echo "Error: python3 required to generate secrets." >&2
    exit 1
fi

ADMIN_SECRET="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
ADMIN_PASSWORD="${ADMIN_API_DEFAULT_ADMIN_PASSWORD:-$(python3 -c 'import secrets; print(secrets.token_urlsafe(16))')}"
LLM_BASE_URL="${AGENT_LLM_BASE_URL:-https://api.deepseek.com}"
LLM_API_KEY="${AGENT_LLM_API_KEY:-change-me}"
LLM_MODEL="${AGENT_LLM_MODEL:-deepseek-chat}"

cat > "$ENV_FILE" <<EOF
# Generated by deploy/prepare-env.sh — do not commit.
ADMIN_API_SECRET_KEY=${ADMIN_SECRET}
ADMIN_API_DEFAULT_ADMIN_PASSWORD=${ADMIN_PASSWORD}
AGENT_LLM_BASE_URL=${LLM_BASE_URL}
AGENT_LLM_API_KEY=${LLM_API_KEY}
AGENT_LLM_MODEL=${LLM_MODEL}
AGENT_RATE_LIMIT_PER_MINUTE=30
AGENT_MAX_SESSION_MESSAGES=100
EOF

chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE"
echo "Admin initial password: ${ADMIN_PASSWORD}"
